# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc72bc355ae33239e0b8b0cb8e711bfd5e28adff967c85bdab49dc408519adc9d959f33b717ddb6bf449477580bafc6cc0de6bfd49bf26468eb8994a99bb943d

test:
  secret_key_base: e21beebfc12a49df10dca8f38d283721de1daf06c1dead7a9f6e796fdfbf95342e2d4054b05ac9a5cc55ed0290b7b183da63d2c2cbcbcc2695de7cda3a896dc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
